name: tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 16 * *'
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  if-does-not-exist:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        cache: [ true, false ]

    steps:
      - uses: actions/checkout@v4

      - name: Remove AWS CLI if installed
        run: sudo rm -rf /usr/local/aws-cli

      - name: Execute this action
        uses: ./
        with:
          cache: ${{ matrix.cache }}

      - run: aws --version

  if-already-exists:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Execute this action
        uses: ./
      - run: aws --version
